import type { WorkspaceSnapshot } from '../types/database'

const now = new Date().toISOString()
const yesterday = new Date(Date.now() - 86_400_000).toISOString()
const lastWeek = new Date(Date.now() - 6 * 86_400_000).toISOString()

export const demoWorkspace: WorkspaceSnapshot = {
  years: [
    {
      id: 'year-1448',
      user_id: 'demo-user',
      label: '1448هـ',
      sort_order: 1,
      is_archived: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'year-1447',
      user_id: 'demo-user',
      label: '1447هـ',
      sort_order: 2,
      is_archived: true,
      created_at: lastWeek,
      updated_at: lastWeek,
    },
  ],
  semesters: [
    {
      id: 'semester-1',
      user_id: 'demo-user',
      academic_year_id: 'year-1448',
      name: 'الفصل الدراسي الأول',
      sort_order: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'semester-2',
      user_id: 'demo-user',
      academic_year_id: 'year-1448',
      name: 'الفصل الدراسي الثاني',
      sort_order: 2,
      created_at: now,
      updated_at: now,
    },
  ],
  tabs: [
    {
      id: 'tab-circulars',
      user_id: 'demo-user',
      semester_id: 'semester-1',
      name: 'التعاميم المنظمة',
      description: 'اللوائح والتعليمات المنظمة لأعمال الاختبارات',
      icon: 'ScrollText',
      accent: 'violet',
      sort_order: 1,
      is_archived: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'tab-committees',
      user_id: 'demo-user',
      semester_id: 'semester-1',
      name: 'تشكيل اللجان',
      description: 'قرارات التشكيل والتكليفات',
      icon: 'UsersRound',
      accent: 'blue',
      sort_order: 2,
      is_archived: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'tab-meetings',
      user_id: 'demo-user',
      semester_id: 'semester-1',
      name: 'اجتماعات الاختبارات',
      description: 'المحاضر والتوصيات ومحاور الاجتماعات',
      icon: 'MessagesSquare',
      accent: 'amber',
      sort_order: 3,
      is_archived: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'tab-questions',
      user_id: 'demo-user',
      semester_id: 'semester-1',
      name: 'أسئلة الاختبارات',
      description: 'نسخ الأسئلة المعتمدة والبديلة',
      icon: 'FileQuestion',
      accent: 'rose',
      sort_order: 4,
      is_archived: false,
      created_at: now,
      updated_at: now,
    },
  ],
  folders: [
    {
      id: 'folder-grade-1',
      user_id: 'demo-user',
      tab_id: 'tab-questions',
      parent_id: null,
      name: 'الصف الأول المتوسط',
      sort_order: 1,
      created_at: now,
      updated_at: now,
    },
  ],
  documents: [
    {
      id: 'document-1',
      user_id: 'demo-user',
      academic_year_id: 'year-1448',
      semester_id: 'semester-1',
      tab_id: 'tab-circulars',
      folder_id: null,
      original_name: 'دليل الاختبارات 1448.pdf',
      display_name: 'دليل الاختبارات 1448.pdf',
      storage_path: 'demo/dalil.pdf',
      mime_type: 'application/pdf',
      extension: 'pdf',
      size_bytes: 4_800_000,
      status: 'ready',
      description: null,
      tags: ['دليل', 'تعليمات'],
      is_favorite: true,
      is_deleted: false,
      deleted_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'document-2',
      user_id: 'demo-user',
      academic_year_id: 'year-1448',
      semester_id: 'semester-1',
      tab_id: 'tab-committees',
      folder_id: null,
      original_name: 'قرار تشكيل لجنة الاختبارات.docx',
      display_name: 'قرار تشكيل لجنة الاختبارات.docx',
      storage_path: 'demo/committee.docx',
      mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      extension: 'docx',
      size_bytes: 630_000,
      status: 'ready',
      description: null,
      tags: ['لجنة'],
      is_favorite: false,
      is_deleted: false,
      deleted_at: null,
      created_at: yesterday,
      updated_at: yesterday,
    },
    {
      id: 'document-3',
      user_id: 'demo-user',
      academic_year_id: 'year-1448',
      semester_id: 'semester-1',
      tab_id: 'tab-meetings',
      folder_id: null,
      original_name: 'محضر الاجتماع الأول.pdf',
      display_name: 'محضر الاجتماع الأول.pdf',
      storage_path: 'demo/meeting.pdf',
      mime_type: 'application/pdf',
      extension: 'pdf',
      size_bytes: 1_260_000,
      status: 'ready',
      description: null,
      tags: ['محضر'],
      is_favorite: false,
      is_deleted: false,
      deleted_at: null,
      created_at: lastWeek,
      updated_at: lastWeek,
    },
    {
      id: 'document-4',
      user_id: 'demo-user',
      academic_year_id: 'year-1448',
      semester_id: 'semester-1',
      tab_id: 'tab-questions',
      folder_id: 'folder-grade-1',
      original_name: 'اختبار الرياضيات.xlsx',
      display_name: 'اختبار الرياضيات.xlsx',
      storage_path: 'demo/math.xlsx',
      mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      extension: 'xlsx',
      size_bytes: 940_000,
      status: 'ready',
      description: null,
      tags: ['رياضيات'],
      is_favorite: false,
      is_deleted: false,
      deleted_at: null,
      created_at: yesterday,
      updated_at: yesterday,
    },
  ],
}
